### PR TITLE
add async HTTP support with 3-arity handler versions

### PR DESCRIPTION
**Pull request by Snurppa**

### CODE REVIEW

**Comment by egs33** [comment]
Thanks for pull request!
It looks very good, but this project does not use vertical alignment style in `let`, map literals, etc.

example for
```clojure
(let [res (handler req)
      header-value (or (when policy-generator
                         (some-> (policy-generator req)
                                 (compose*)))
                       default-policy)]
  (assoc-in res [:headers header-name] header-value))

{:default-src [:self]
 :block-all-mixed-content true
 :script-src [:self]}
```

Could you adjust this style?

**Comment by Snurppa** [comment]
Yeah, of course! Will get back to this later today 👍

**Comment by Snurppa** [comment]
Ok @egs33 , just force pushed the commit with styles aligned.

**Comment by egs33** [comment]
Thank you!

**Pull request merged**
